spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hhd_blog_db?user=root

    username: root
    password: akiraphung
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 972871875289-iq458icd9hbpr16338o6cik7ajc48c2s.apps.googleusercontent.com
            clientSecret: -L93mVfd6QRZT_MpIuhmqhpv
            scope:
              - email
              - profile